export const SET_AUTHED_USER = 'SET_AUTHED_USER'

export const ADD_QUESTION = 'ADD_QUESTION'
export const ADD_ANSWER = 'ADD_ANSWER'

export const USER_ADD_QUESTION = 'USER_ADD_QUESTION'
export const USER_ADD_ANSWER = 'USER_ADD_ANSWER'

export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const RECEIVE_USERS = 'RECEIVE_USERS'

export const SET_LOADING = 'SET_LOADING'
export const RESET_LOADING = 'RESET_LOADING'
